#ifndef _LABELING_BLOCKS_
#define _LABELING_BLOCKS_

#include "procedures2x2.h"

#define ePROCEDURE1aeR1	_ePROCEDURE1aeR1(PIXEL_H,PIXEL_I,PIXEL_J,LABEL_BLOCK_A,LABEL_BLOCK_B,LABEL_BLOCK_B)
#define ePROCEDURE1aeR0	_ePROCEDURE1aeR0(PIXEL_H,PIXEL_I,PIXEL_J,LABEL_BLOCK_A,LABEL_BLOCK_B,LABEL_BLOCK_B)
#define ePROCEDURE1bR0c _ePROCEDURE1bR0c
#define ePROCEDURE1fR1 	_ePROCEDURE1fR1_BLOCKS
#define ePROCEDURE1fR0g	_ePROCEDURE1fR0g_BLOCKS

#define ePROCEDURE2aef 	_ePROCEDURE2aef(PIXEL_H,PIXEL_I,PIXEL_J,LABEL_BLOCK_B,LABEL_BLOCK_B)
#define ePROCEDURE2bd 	_ePROCEDURE2bd(PIXEL_H,PIXEL_I,LABEL_BLOCK_B)
#define ePROCEDURE2c 	_ePROCEDURE2c(PIXEL_H,PIXEL_I,LABEL_BLOCK_B)
#define ePROCEDURE2g 	_ePROCEDURE2g(PIXEL_H,PIXEL_I,PIXEL_J,LABEL_BLOCK_B,LABEL_BLOCK_B)


#define LABELING_ALL_CASES LABEL_BLOCK_E = lab;
#define LABELING_CASE_A LABELING_ALL_CASES
#define LABELING_CASE_B LABELING_ALL_CASES
#define LABELING_CASE_C LABELING_ALL_CASES
#define LABELING_CASE_E LABELING_ALL_CASES
#define LABELING_CASE_F LABELING_ALL_CASES
#define LABELING_CASE_G LABELING_ALL_CASES
#define LABELING_CASE_FG LABELING_ALL_CASES
#define LABELING_CASE_EF LABELING_ALL_CASES


//HCS
#define hLABELING hLABEL_BLOCK_E = lab;

#define hPROCEDURE1a \
    _PROCEDURE1a(PIXEL_H,PIXEL_I,PIXEL_J,PIXEL_R,hLABEL_BLOCK_A,hLABEL_BLOCK_B,hLABEL_BLOCK_C) \
    hLABELING

#define hPROCEDURE1b \
    _PROCEDURE1b(PIXEL_R) \
    hLABELING

#define hPROCEDURE2a \
    _PROCEDURE2a(PIXEL_I,PIXEL_J,hLABEL_BLOCK_C) \
    hLABELING

#define hPROCEDURE2b hLABELING

#define hPROCEDURE2bc hLABEL_BLOCK_E = *lb[imgInNextL[j]];

#endif
